apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-postgis.fullname" . }}-secret
  labels:
    {{- include "postgres-postgis.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-username: {{ .Values.auth.username | b64enc | quote }}
  postgres-password: {{ .Values.auth.password | b64enc | quote }}
