apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-db-secret
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}?schema=public"
