apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}-db-secret
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}?schema=public"
  jwt-secret: {{ .Values.jwt.secret | quote }}
  internal-notification-api-key: {{ .Values.internalNotificationApiKey | quote }}
  internal-identity-api-key: {{ .Values.internalIdentityApiKey | quote }}
  smtp-host: ""
  smtp-port: "587"
  smtp-secure: "false"
  smtp-user: ""
  smtp-pass: ""
  smtp-from: ""
